version = 1

test_patterns = ["src/treq/test/test_*.py"]

exclude_patterns = [
    "changelog.d/**",
    "docs/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
