# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  fail_on_warning: false

formats:
  - pdf
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
