[tox]
envlist =
    py39-twisted_lowest,
    {pypy3,py39,py310,py311,py312,py313,py314}-twisted_latest,
    {pypy3,py310,py311,py312,py313,py314}-twisted_trunk,
    check-manifest, flake8, docs, coverage-report
isolated_build = true

[testenv]
extras = dev
deps =
    coverage

    twisted_lowest: Twisted[tls]==22.10.0
    # Older Twisted doesn't work with pyOpenSSL that incorporates this fix.
    # https://github.com/pyca/pyopenssl/pull/1416
    twisted_lowest: pyOpenSSL<26.2.0

    twisted_latest: Twisted[tls]
    twisted_trunk: https://github.com/twisted/twisted/archive/trunk.zip
setenv =
    # Avoid unnecessary network access when creating virtualenvs for speed.
    VIRTUALENV_NO_DOWNLOAD=1
    PIP_DISABLE_PIP_VERSION_CHECK=1
passenv = TERM  # ensure colors
commands =
    pip list
    python -Wall \
    {envbindir}/coverage run -p \
    {envbindir}/trial --temp-directory={envtmpdir}/_trial_temp {posargs:treq}

[testenv:mypy]
basepython = python3.14
deps =
    mypy==2.1.0
    mypy-zope==1.0.15
commands =
    mypy \
        --cache-dir="{toxworkdir}/mypy_cache" \
        {tty:--pretty:} \
        {posargs:src}

[testenv:flake8]
python = python3.14
skip_install = True
deps = flake8
commands = flake8 src/treq/ docs/examples/

[testenv:towncrier]
python = python3.14
deps =
    towncrier
commands =
    towncrier {posargs:--draft}

[testenv:twine]
python = python3.14
deps =
    twine
commands =
    twine check {distdir}/*.*

[testenv:check-manifest]
python = python3.14
deps =
    check-manifest
commands =
    check-manifest

[testenv:docs]
extras = docs
changedir = docs
basepython = python3.14
commands =
    sphinx-build -b html . html

[testenv:coverage-report]
depends = pypy3,py39,py310,py311,py312,py313,py314
commands =
    coverage combine
    coverage report

[flake8]
# This is a minimal Black-compatible config.
# See https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8
# Also disable E501 line length enforcement because it handled by Black's formatting.
max-line-length = 88
extend-ignore = E203, W503, E501, E701
