# src for treq (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from treq.api import delete as delete, get as get, head as head, patch as patch, post as post, put as put, request as request
from treq.content import collect as collect, content as content, json_content as json_content, text_content as text_content
