# src for treq.content (Python 3)
from typing import Any, Callable

from twisted.internet.defer import Deferred
from twisted.internet.protocol import Protocol
from twisted.python.failure import Failure
from twisted.web.iweb import IResponse

class _BodyCollector(Protocol):
    finished: Deferred[None] = ...
    collector: Callable[[str], Any] = ...
    def __init__(
        self, finished: Deferred[None], collector: Callable[[str], Any]
    ) -> None: ...
    def dataReceived(self, data: bytes) -> None: ...
    def connectionLost(self, reason: Failure) -> None: ...

def collect(response: IResponse, collector: Callable[[str], Any]) -> Deferred[None]: ...
def content(response: IResponse) -> Deferred[bytes]: ...
def json_content(response: IResponse, **kwargs: Any) -> Deferred[Any]: ...
def text_content(response: IResponse, encoding: str = ...) -> Deferred[str]: ...
